
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'adie/BlockDiff'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 't9md/vim-quickhl.git'
hook_add = '''
  nmap <Space>m <Plug>(quickhl-manual-this)
  xmap <Space>m <Plug>(quickhl-manual-this)
  nmap <Space>M <Plug>(quickhl-manual-reset)
  xmap <Space>M <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  " ホームポジションに近いキーを使う
  let g:EasyMotion_keys='hjklasdfgyuiopqwertnmzxcvbHJKLASDFGYUIOPQWERTNMZXCVB'
  " 「'」 + 何かにマッピング
  let g:EasyMotion_leader_key="<SPACE>"
  " 1 ストローク選択を優先する
  let g:EasyMotion_grouping=1
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized.git'
hook_add = '''
  let g:solarized_termtrans=1
  " call togglebg#map('<F3>')
'''
